feito a home e os links para ela
MrFonseca/shoplist pull request #7
Opened 2017-01-03 17:51 UTC by MrFonseca

Criado Home com links para as páginas de categories, items e lists.
Criado links dessas páginas para Home.

2017-01-03 19:39 UTC, gabrielhilal requested changes

2017-01-03 19:39 UTC, gabrielhilal commented on app/controllers/staticpages_controller.rb
> +class StaticpagesController < ApplicationController
@MrFonseca aqui deveria ser `StaticPagesController`, e o nome do arquivo `static_pages_controller.rb`

2017-01-03 19:39 UTC, gabrielhilal commented on app/views/staticpages/home.html.erb
> +<h1>Shop List</h1>
o nome dessa pasta `.../static_pages/home.html.erb`

2017-01-03 19:39 UTC, gabrielhilal commented on config/routes.rb
> +  root 'staticpages#home'
e aqui` root 'static_pages#home'`

2017-01-04 11:23 UTC, gabrielhilal commented on app/views/static_pages/home.html.erb
> +<p><%= link_to 'Categorias', controller: 'categories' %></p>
cara, tenta sempre usar os link helpers... se tu rodar `rake routes` tu vai ver eles i.e `categories`, `items`, etc...
Ai tu usa com o `_path` i.e `categories_path`, `items_path`, etc

2017-01-04 12:15 UTC, MrFonseca commented
@gabrielhilal 
Olha aí as mudanças. Acho que já está apto pra merge.

2017-01-04 12:21 UTC, merged